import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export interface Layoutprops {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Layoutprops>) {
  return (
    <html lang="en">
      <body className={`${inter.className} w-full max-w-screen-sm mx-auto`}>{children}</body>
    </html>
  );
}